[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
web = { path = "../web" }

hyper = "0.14.18"
tokio = { version = "1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.2"
